plugins {
    id "com.android.application"
}

android {
    namespace "com.trianglehealthykitchen.preview"
    compileSdk 35

    defaultConfig {
        applicationId "com.trianglehealthykitchen.preview"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "1.2-preview"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
