import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRtl: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_packages: 'Plans',
    nav_menu: 'Menu',
    nav_how_it_works: 'How it works',
    nav_contact: 'Contact',
    nav_my_plan: 'My Plan',
    nav_book: 'Book Consultation',

    // Navigation & Tabs
    Today: 'My Rhythm',
    Community: 'Community',
    Rewards: 'Rewards',
    Profile: 'Profile',
    'Kitchen Ops': 'Kitchen Ops',
    'Kitchen Ops Center': 'Kitchen Ops Center',
    'Main Site': 'Main Site',
    menu: 'Menu',
    delivery: 'Delivery',
    health: 'Health',
    settings: 'Settings',

    // Hero
    hero_title_1: 'Your Chef.',
    hero_title_2: 'Your Plan.',
    hero_title_3: 'Your Results.',
    hero_subtitle: 'Triangle Healthy Kitchen delivers healthy, chef-made meals to your door daily in Doha.',
    hero_cta_book: 'Start Plan',
    hero_cta_packages: 'View Plans',
    est_2017: 'Est. 2017',
    doha_excellence: 'Doha Excellence',
    doha_standard: 'Doha Standard',
    active_members: 'Active Members',
    collections: 'Collections',
    chef_support: 'Chef Support',
    transformation_title: 'Start your journey.',
    transformation_subtitle: 'Get your personal healthy meal plan today.',
    seven_plus: '7+',
    five_hundred_plus: '500+',
    twelve_plus: '12+',
    twenty_four_seven: '24/7',
    scroll: 'Scroll',
    explore_collections: 'Explore Collections',
    view_collections: 'View Collections',
    premium_experience: 'Healthy Experience',
    precision_protocol: 'Precision Plan',
    visual_heritage: 'Our Heritage',
    precision_standard: 'Quality Standard',
    crafting_legacy: 'Your Health Journey',
    begin_wellness: 'Start your healthy chapter',
    doha_community_desc: 'Join the Doha community focused on healthy eating. Get your plan today.',
    start_today: 'Start Today',
    view_menu: 'View Menu',
    all_rights_reserved: 'All Rights Reserved',
    healthy_mind_subtitle: 'CLARITY',
    healthy_body_subtitle: 'VITALITY',
    healthy_soul_subtitle: 'BALANCE',
    triangle_philosophy: 'Triangle Philosophy',
    one_triangle: 'One Triangle',
    three_pillars: 'Three Pillars',
    mind_clarity_desc: 'Clear mind through healthy food.',
    body_vitality_desc: 'Feel better with whole foods.',
    soul_balance_desc: 'Balance in every dish.',
    visual_transparency_desc: 'Fresh ingredients. Excellent delivery.',
    chef_crafted_title: 'Chef Made',
    portion_control_title: 'Right Portions',
    expert_quality_title: 'Best Quality',
    fresh_macro_meals: 'Fresh healthy meals prepared daily',
    simple_support: 'Support for your health and wellness',
    cleaner_path: 'A simple way to get results',
    identity_label: 'YOUR PROFILE',
    key_label: 'KEY',
    authenticating: 'CHECKING...',
    access_dashboard: 'OPEN DASHBOARD',
    secure_gateway: 'Secure Payment',
    fleet_online: 'Delivery Online',
    manual_assignment: 'Manual Assignment',
    active_revenue: 'Active Revenue',
    verified_units: 'Verified Units',
    active_ops: 'Active Ops',
    revenue_pulse: 'Weekly Overview',
    refresh_signal: 'Refresh',
    find_identity: 'Find Profile...',
    assign_rider: 'Assign Driver',
    terminate_session: 'Logout',
    fully_booked: 'FULLY BOOKED',
    status_full: 'FULL',
    delivery_protocol: 'Delivery Plan',
    revenue: 'Revenue',
    awaiting_signal: 'Connecting...',
    realtime: 'LIVE',
    operational_intelligence: 'Kitchen Info',
    precision: 'Quality',
    online: 'Online',
    offline: 'Offline',
    approval_pending: 'Waiting for Approval',
    rider_verification_desc: 'Your account is being checked. Please wait.',
    assigned_stops: 'Assigned Deliveries',
    route_intelligence: 'Route Info',
    live_logistics: 'Live Delivery',
    gps_active: 'GPS Active',
    syncing_command: 'Connecting to Kitchen',
    todays_goal: 'Today\'s Goal',
    efficiency: 'Efficiency',
    stops: 'Deliveries',
    no_active_deliveries: 'No deliveries right now.',
    export_kitchen_prep: 'Export Kitchen Prep',
    prep_list_desc: 'Get the meal list for the Doha kitchen.',
    execute_bulk_assign: 'Assign All Drivers',
    bulk_assign_desc: 'Connect all members to drivers.',
    live_fleet_logistics: 'Live Delivery Map',
    total_label: 'Total',
    active_pulse: 'Live',
    muted_label: 'Muted',
    critical_intel: 'Health Info',
    dietary_restrictions: 'Allergies',
    exercise_routine: 'Exercise',
    health_notes: 'Health Notes',
    clinical_context: 'Healthy Context',
    duration_protocol: 'Plan Duration',
    days_count: 'Active Meal Days',
    duration_daily: 'Daily Trial',
    duration_weekly: 'Weekly Reset',
    duration_monthly: 'Monthly Plan',
    price_calculation: 'Simple Pricing',
    convenience_fee: 'Delivery Included',

    // About & Simplification
    what_is_triangle: 'What is Triangle?',
    what_get: 'What do I get?',
    what_get_desc: 'Fresh breakfast, lunch, and dinner. Macro-counted. No cooking, no cleaning.',
    what_cost: 'How much does it cost?',
    starting_from: 'From QR 180/day',
    how_start: 'How do I start?',
    step_1: 'Pick a Plan',
    step_2: 'Share Allergies',
    step_3: 'Get Food',
    about_title: 'Healthy Meals, Delivered.',
    about_text_1: 'Since 2017, Triangle has been Doha\'s top choice for healthy meals.',
    about_text_2: 'We make fresh, tasty food to help you feel your best.',
    food_safety: 'Food Safety',
    food_safety_desc: 'Municipality Approved',
    bio_science: 'Healthy Science',
    bio_science_desc: 'Dietitian Led',
    artisanal: 'Chef Made',
    artisanal_desc: 'Fresh Every Day',
    logistics: 'Deliveries & Drivers',
    logistics_desc: 'GPS Tracked',
    years_of_excellence: 'Years in Doha',
    chef_crafted: 'Chef-Made',
    chef_crafted_desc: 'Fresh in our Doha kitchen',
    bio_aligned: 'Health-Matched',
    bio_aligned_desc: 'Made for your body',
    performance_focus: 'Feel Better',
    performance_focus_desc: 'Fuel for your mind and body',
    direct_service: 'Daily Delivery',
    direct_service_desc: 'To your door, 365 days',

    // Packages
    packages_title: 'Pick your Plan',
    packages_subtitle: 'Select the plan that fits your goals and energy.',
    '1100kcal': 'Essential Plan',
    '1400kcal': 'Daily Balance',
    '1500kcal': 'Performance Plan',
    signature_custom: 'Custom Plan',
    essential: 'Essential Plan',
    balance: 'Daily Balance',
    performance: 'Performance Plan',
    '1100kcal_desc': 'A simple, healthy plan to help you lose weight.',
    '1400kcal_desc': 'The perfect daily plan for balance and energy.',
    '1500kcal_desc': 'A personalized plan for active people.',
    tribe_status: 'Member Status',
    bio_boost_immunity: 'Immunity Boost (Ginger/Turmeric)',
    bio_boost_collagen: 'Collagen Boost',
    sunday_reset: 'Maintain your progress for rewards.',
    signature_desc: 'Our best plan. Pick your own monthly menu.',
    daily_trial: '1 Day Pass',
    weekly_reset: '6 Day Pass',
    daily_trial_desc: '1 day of healthy meals. Great to try.',
    weekly_reset_desc: '6 days of healthy meals for your work week.',
    full_day_supply: 'Full Day of Meals',
    '6_day_supply': '6 Days of Meals',
    flexible_meals: 'Pick your meals',
    quick_access: 'Quick Access',
    short_term_focus: 'Short Term',
    best_for_weight_loss: 'Best for weight loss',
    for_active_lifestyles: 'For active people',
    bespoke_menu: 'Choose your menu',
    '4_weeks_flex': '4 Weeks (Full flexibility)',
    '2_meals_1_snack': '2 Meals + 1 Snack',
    '3_main_meals': '3 Main Meals',
    '3_meals_1_snack': '3 Meals + 1 Snack',
    '4_weeks_28_boxes': '4 Weeks (28 meals)',
    '4_weeks_28_boxes_pers': '4 Weeks (Personalized meals)',
    calories_per_day: 'Calories Per Day',
    balanced_nutrients: 'Balanced Nutrition',
    continuous_delivery: 'Daily Delivery',
    chef_tailored: 'Chef Made',
    based_on_metrics: 'Made for you',
    most_popular: 'Most Popular',
    premium: 'Healthy',
    login: 'Login',
    join: 'Join',
    qar: 'QAR',
    free_consultation: 'Free Chat',
    consultation: 'Chat',
    questions: 'Questions?',

    // How It Works
    how_it_works_title: 'How to Start',
    how_it_works_subtitle: 'Four simple steps to get your healthy food.',
    hiw_step1_title: 'Sign Up',
    hiw_step1_desc: 'Book your spot in 60 seconds.',
    hiw_step2_title: 'Your Health Info',
    hiw_step2_desc: 'Share your info for the perfect plan.',
    hiw_step3_title: 'Chef Plan',
    hiw_step3_desc: 'We create a meal plan for your goals.',
    hiw_step4_title: 'Daily Meals',
    hiw_step4_desc: 'Fresh meals delivered daily to your door.',
    start_journey: 'Start Now',
    hero_cta_book_free: 'Book a Free Chat',
    hero_cta_subscribe_now: 'Subscribe Now →',
    members_count: 'Members',
    cities_count: 'Cities',
    plans_count: 'Plans',
    Excellent_experience: 'Happy with us?',
    perfected: 'Perfected',
    rate_our_service: 'Rate Us',
    request_account_deletion: 'Delete Account',
    weight_loss_match: 'Weight Loss',
    muscle_gain_match: 'Muscle Gain',
    heritage_choice: 'Local Choice',

    // Mission
    mission_title: 'Our Mission',
    mission_intro: "We want to help you have a healthy mind, body, and soul",
    healthy_mind_title: "Healthy Mind",
    healthy_mind_desc: "We make meals that help you stay clear and happy.",
    healthy_body_title: "Healthy Body",
    healthy_body_desc: "Our meals give you energy and keep you healthy.",
    healthy_soul_title: "Healthy Soul",
    healthy_soul_desc: "We believe in good food and a good community.",
    mission_closing: "Healthy eating changes lives. We help you be your best.",

    // Community Tribe Keys
    tribe_title: 'The Tribe',
    collective_ecosystem: 'Collective Ecosystem',
    privacy_discovery: 'Privacy-First Discovery',
    group_near_you: 'A group near your rhythm',
    team_vitality: 'Team Vitality',
    daily_goal: 'Daily Goal',
    join_community: 'Join Group',
    regional_collectives: 'Regional Collectives',
    active_collective: 'Active Collective',
    collective_momentum: 'Collective Momentum',
    collective_rewards_desc: 'Group participation unlocks shared weekly rewards.',
    leaderboard: 'Fair Leaderboard',
    encouragement_feed: 'Encouragement Feed',
    regional_pulses: 'Regional Pulses',
    share_progress: 'Share Progress',
    completed: 'Completed',

    // Dashboard & Rhythm Keys
    keep_the_pace: 'Keep The Pace',
    weekly_streak: 'Weekly Streak',
    next_milestone: 'Next Milestone',
    daily_activity: 'Daily Activity',
    your_dashboard: 'Your Dashboard',
    essential_plan_access: 'Essential Plan Access',
    progress: 'Progress',
    access_label: 'Access',
    goal_label: 'Goal',
    steps_label: 'Steps',
    days_label: 'Days',
    balance_label: 'Balance',
    sync_now_btn: 'Sync Now',
    ops_command: 'Kitchen Operations',
    live_feed: 'Activity Feed',
    inquiries: 'Bookings & Inquiries',
    members: 'Subscribers',

    // Loading Screen
    securing_protocol: 'Starting...',
    encrypting_session: 'Checking profile',
    biometric_link: 'Connected',

    // Identity & Translation Sweep Keys
    'start your transformation': 'Start your journey',
    'define your biology': 'Enter your health info',
    'editorial panel': 'Kitchen Panel',

    // Operational Center Keys
    'active subscribers': 'Active Subscribers',
    'est. monthly revenue': 'Est. Monthly Revenue',
    'total inquiries': 'Total Inquiries',
    'approved drivers': 'Approved Drivers',
    'weekly order volume & revenue': 'Weekly Order Volume & Revenue',
    'revenue trend based on active subscriber meal selections across doha': 'Revenue trend based on active subscriber meal selections across Doha',
    'recent activity stream': 'Recent Activity Stream',
    'export kitchen csv': 'Export Kitchen CSV',
    'fleet drivers & approvals': 'Fleet Drivers & Approvals',
    'approved driver': 'Approved Driver',
    'pending approval': 'Pending Approval',
    'approve driver': 'Approve Driver',
    'revoke approval': 'Revoke Approval',
    'search bookings by name or email...': 'Search bookings by name or email...',
    'search subscribers by name, area, email...': 'Search subscribers by name, area, email...',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_about: 'عن المثلث',
    nav_packages: 'الخطط',
    nav_menu: 'المنيو',
    nav_how_it_works: 'كيف نبدأ',
    nav_contact: 'اتصل بنا',
    nav_my_plan: 'خطتي',
    nav_book: 'حجز موعد',

    // Navigation & Tabs
    Today: 'إيقاعي اليومي',
    Community: 'المجتمع',
    Rewards: 'المكافآت',
    Profile: 'الملف الشخصي',
    'Kitchen Ops': 'عمليات المطبخ',
    'Kitchen Ops Center': 'مركز عمليات المطبخ',
    'Main Site': 'الموقع الرئيسي',
    menu: 'المنيو',
    delivery: 'التوصيل',
    health: 'الصحة',
    settings: 'الإعدادات',

    // Hero
    hero_title_1: 'شيفك الخاص.',
    hero_title_2: 'خطتك الغذائية.',
    hero_title_3: 'نتائجك.',
    hero_subtitle: 'وجبات صحية من تحضير الشيف، تصلك يومياً لباب منزلك في الدوحة.',
    hero_cta_book: 'ابدأ الخطة',
    hero_cta_packages: 'عرض الخطط',
    est_2017: 'منذ ٢٠١٧',
    doha_excellence: 'تميز الدوحة',
    doha_standard: 'معيار الدوحة',
    active_members: 'أعضاء نشطون',
    collections: 'المجموعات',
    chef_support: 'دعم الشيف',
    transformation_title: 'ابدأ رحلتك',
    transformation_subtitle: 'احصل على خطة وجباتك الصحية اليوم.',
    seven_plus: '+٧',
    five_hundred_plus: '+٥٠٠',
    twelve_plus: '+١٢',
    twenty_four_seven: '٢٤/٧',
    scroll: 'مرر',
    explore_collections: 'استكشاف المجموعات',
    view_collections: 'عرض المجموعات',
    premium_experience: 'تجربة صحية',
    precision_protocol: 'خطة دقيقة',
    visual_heritage: 'تراثنا',
    precision_standard: 'معيار الجودة',
    crafting_legacy: 'رحلتك الصحية',
    begin_wellness: 'ابدأ حياة صحية',
    doha_community_desc: 'انضم لمجتمع الدوحة المهتم بالأكل الصحي. احصل على خطتك اليوم.',
    start_today: 'ابدأ اليوم',
    view_menu: 'عرض المنيو',
    all_rights_reserved: 'جميع الحقوق محفوظة',
    healthy_mind_subtitle: 'وضوح',
    healthy_body_subtitle: 'حيوية',
    healthy_soul_subtitle: 'توازن',
    triangle_philosophy: 'فلسفة المثلث',
    one_triangle: 'مثلث واحد',
    three_pillars: 'ثلاثة ركائز',
    mind_clarity_desc: 'عقل صافٍ من خلال أكل صحي.',
    body_vitality_desc: 'نشاط من خلال الأكل الطبيعي.',
    soul_balance_desc: 'توازن في كل طبق.',
    visual_transparency_desc: 'مكونات طازجة. توصيل ممتاز.',
    chef_crafted_title: 'من تحضير الشيف',
    portion_control_title: 'حصص مناسبة',
    expert_quality_title: 'أفضل جودة',
    fresh_macro_meals: 'وجبات صحية طازجة يومياً',
    simple_support: 'دعم لصحتك وعافيتك',
    cleaner_path: 'طريقة بسيطة لنتائج حقيقية',
    identity_label: 'ملفك الشخصي',
    key_label: 'المفتاح',
    authenticating: 'جاري التحقق...',
    access_dashboard: 'لوحة التحكم',
    secure_gateway: 'دفع آمن',
    fleet_online: 'التوصيل متصل',
    manual_assignment: 'تعيين يدوي',
    active_revenue: 'الإيرادات',
    verified_units: 'الوحدات',
    active_ops: 'العمليات',
    revenue_pulse: 'نبض الإيرادات',
    refresh_signal: 'تحديث',
    find_identity: 'بحث عن ملف...',
    assign_rider: 'تعيين سائق',
    terminate_session: 'خروج',
    fully_booked: 'مكتمل',
    status_full: 'مكتمل',
    delivery_protocol: 'خطة التوصيل',
    revenue: 'إيرادات',
    awaiting_signal: 'جاري الاتصال...',
    realtime: 'مباشر',
    operational_intelligence: 'معلومات المطبخ',
    precision: 'جودة',
    online: 'متصل',
    offline: 'غير متصل',
    approval_pending: 'بانتظار الموافقة',
    rider_verification_desc: 'يتم فحص حسابك. يرجى الانتظار.',
    assigned_stops: 'توصيلات محددة',
    route_intelligence: 'معلومات المسار',
    live_logistics: 'توصيل مباشر',
    gps_active: 'GPS نشط',
    syncing_command: 'الاتصال بالمطبخ',
    todays_goal: 'هدف اليوم',
    efficiency: 'الكفاءة',
    stops: 'توصيلات',
    no_active_deliveries: 'لا يوجد توصيلات الآن.',
    export_kitchen_prep: 'تصدير تحضير المطبخ',
    prep_list_desc: 'احصل على قائمة الوجبات لمطبخ الدوحة.',
    execute_bulk_assign: 'تعيين جميع السائقين',
    bulk_assign_desc: 'ربط جميع الأعضاء بالسائقين.',
    live_fleet_logistics: 'خريطة التوصيل المباشر',
    total_label: 'الإجمالي',
    active_pulse: 'مباشر',
    muted_label: 'صامت',
    critical_intel: 'معلومات صحية',
    dietary_restrictions: 'حساسية',
    exercise_routine: 'تمرين',
    health_notes: 'ملاحظات صحية',
    clinical_context: 'سياق صحي',
    duration_protocol: 'مدة الخطة',
    days_count: 'أيام الوجبات',
    duration_daily: 'تجربة يومية',
    duration_weekly: '٦ أيام',
    duration_monthly: 'خطة شهرية',
    price_calculation: 'تسعير بسيط',
    convenience_fee: 'شامل التوصيل',

    // About & Simplification
    what_is_triangle: 'ما هو المثلث؟',
    what_get: 'ماذا أحصل؟',
    what_get_desc: 'إفطار وغداء وعشاء طازج. بدون طبخ أو تنظيف.',
    what_cost: 'ما هي التكلفة؟',
    starting_from: 'يبدأ من ١٨٠ ريال قطري يومياً',
    how_start: 'كيف أبدأ؟',
    step_1: 'اختر خطة',
    step_2: 'أخبرنا بالحساسية',
    step_3: 'احصل على الطعام',
    about_title: 'وجبات صحية، تصلك لبابك.',
    about_text_1: 'منذ عام ٢٠١٧، المثلث هو الخيار الأول للوجبات الصحية في الدوحة.',
    about_text_2: 'نحضر وجبات طازجة ولذيذة لتشعر بأفضل حالاتك.',
    food_safety: 'سلامة الغذاء',
    food_safety_desc: 'معتمد من البلدية',
    bio_science: 'علوم صحية',
    bio_science_desc: 'بإشراف أخصائي تغذية',
    artisanal: 'شيف خاص',
    artisanal_desc: 'طازج يومياً',
    logistics: 'توصيل وسائقين',
    logistics_desc: 'تتبع GPS',
    years_of_excellence: 'سنوات في الدوحة',
    chef_crafted: 'من تحضير الشيف',
    chef_crafted_desc: 'طازج في مطبخنا بالدوحة',
    bio_aligned: 'متوافق مع صحتك',
    bio_aligned_desc: 'مصمم لجسمك',
    performance_focus: 'اشعر بتحسن',
    performance_focus_desc: 'طاقة لعقلك وجسمك',
    direct_service: 'توصيل يومي',
    direct_service_desc: 'لباب منزلك، ٣٦٥ يوماً',

    // Packages
    packages_title: 'اختر خطتك',
    packages_subtitle: 'اختر الخطة التي تناسب أهدافك ونشاطك.',
    '1100kcal': 'الخطة الأساسية',
    '1400kcal': 'التوازن اليومي',
    '1500kcal': 'خطة الأداء',
    signature_custom: 'خطة مخصصة',
    essential: 'الخطة الأساسية',
    balance: 'التوازن اليومي',
    performance: 'خطة الأداء',
    '1100kcal_desc': 'خطة صحية بسيطة لمساعدتك على فقدان الوزن.',
    '1400kcal_desc': 'الخطة اليومية المثالية للتوازن والطاقة.',
    '1500kcal_desc': 'خطة مخصصة للأشخاص النشطين.',
    tribe_status: 'حالة العضو',
    bio_boost_immunity: 'تعزيز المناعة (زنجبيل/كركم)',
    bio_boost_collagen: 'تعزيز الكولاجين',
    sunday_reset: 'حافظ على تقدمك للحصول على مكافآت.',
    signature_desc: 'أفضل خططنا. اختر المنيو الشهري الخاص بك.',
    daily_trial: 'تصريح يوم واحد',
    weekly_reset: 'تصريح ٦ أيام',
    daily_trial_desc: 'يوم واحد من الوجبات الصحية. رائعة للتجربة.',
    weekly_reset_desc: '٦ أيام من الوجبات الصحية لأسبوع عملك.',
    full_day_supply: 'وجبات يوم كامل',
    '6_day_supply': 'وجبات ٦ أيام',
    flexible_meals: 'اختر وجباتك',
    quick_access: 'وصول سريع',
    short_term_focus: 'مدى قصير',
    best_for_weight_loss: 'الأفضل لفقدان الوزن',
    for_active_lifestyles: 'للأشخاص النشطين',
    bespoke_menu: 'اختر المنيو الخاص بك',
    '4_weeks_flex': '٤ أسابيع (مرونة كاملة)',
    '2_meals_1_snack': 'وجبتين + سناك واحد',
    '3_main_meals': '٣ وجبات رئيسية',
    '3_meals_1_snack': '٣ وجبات + سناك واحد',
    '4_weeks_28_boxes': '٤ أسابيع (٢٨ وجبة)',
    '4_weeks_28_boxes_pers': '٤ أسابيع (وجبات مخصصة)',
    calories_per_day: 'سعرة حرارية يومياً',
    balanced_nutrients: 'تغذية متوازنة',
    continuous_delivery: 'توصيل يومي',
    chef_tailored: 'من تحضير الشيف',
    based_on_metrics: 'مصمم لك',
    most_popular: 'الأكثر شعبية',
    premium: 'صحي',
    login: 'دخول',
    join: 'انضم',
    qar: 'ريال قطري',
    free_consultation: 'دردشة مجانية',
    consultation: 'دردشة',
    questions: 'أسئلة؟',

    // How It Works
    how_it_works_title: 'كيف نبدأ',
    how_it_works_subtitle: 'أربع خطوات بسيطة للحصول على وجباتك الصحية.',
    hiw_step1_title: 'سجل الآن',
    hiw_step1_desc: 'احجز مكانك في ٦٠ ثانية.',
    hiw_step2_title: 'معلوماتك الصحية',
    hiw_step2_desc: 'شاركنا بياناتك للخطة المثالية.',
    hiw_step3_title: 'خطة الشيف',
    hiw_step3_desc: 'نصمم خطة وجبات تناسب أهدافك.',
    hiw_step4_title: 'وجبات يومية',
    hiw_step4_desc: 'وجبات طازجة تصلك يومياً لباب منزلك.',
    start_journey: 'ابدأ الآن',
    hero_cta_book_free: 'احجز دردشة مجانية',
    hero_cta_subscribe_now: 'اشترك الآن ←',
    members_count: 'عضو',
    cities_count: 'مدن',
    plans_count: 'خطط',
    Excellent_experience: 'سعيد معنا؟',
    perfected: 'متقنة',
    rate_our_service: 'قيمنا',
    request_account_deletion: 'حذف الحساب',
    weight_loss_match: 'فقدان وزن',
    muscle_gain_match: 'بناء عضلات',
    heritage_choice: 'خيار محلي',

    // Mission
    mission_title: 'مهمتنا',
    mission_intro: "نريد مساعدتك للحصول على عقل وجسد وروح صحية",
    healthy_mind_title: "عقل سليم",
    healthy_mind_desc: "نحضر وجبات تساعدك على البقاء صافياً وسعيداً.",
    healthy_body_title: "جسم سليم",
    healthy_body_desc: "وجباتنا تمنحك الطاقة وتحافظ على صحتك.",
    healthy_soul_title: "روح سليمة",
    healthy_soul_desc: "نؤمن بالطعام الجيد والمجتمع الجيد.",
    mission_closing: "الأكل الصحي يغير الحياة. نساعدك لتكون الأفضل.",

    // Community Tribe Keys
    tribe_title: 'قبيلة المثلث',
    collective_ecosystem: 'مجتمعنا الصحي',
    privacy_discovery: 'اكتشاف المجموعات',
    group_near_you: 'مجموعة قريبة من منطقتك',
    team_vitality: 'نشاط الفريق',
    daily_goal: 'الهدف اليومي',
    join_community: 'الانضمام للمجموعة',
    regional_collectives: 'المجموعات الإقليمية',
    active_collective: 'المجموعة النشطة',
    collective_momentum: 'زخم الفريق',
    collective_rewards_desc: 'مشاركة الفريق تفتح مكافآت أسبوعية مشتركة.',
    leaderboard: 'لوحة الصدارة',
    encouragement_feed: 'سجل التفاعل والتشجيع',
    regional_pulses: 'تحديثات المناطق',
    share_progress: 'مشاركة التقدم',
    completed: 'مكتمل',

    // Errors & Flow
    membership: 'العضوية',
    subscription: 'الاشتراك',
    discovery: 'الاكتشاف',
    personal_assessment: 'معلوماتك الصحية',
    define_bio_parameters: 'أدخل بياناتك لخطتك الغذائية.',
    ambition: 'الهدف',
    energy_output: 'النشاط',
    assessment_analysis: 'تقييم',
    kcal_target: 'هدف السعرات اليومي',
    protein: 'بروتين',
    carbs: 'كربوهيدرات',
    lipids: 'دهون',
    weight: 'الوزن',
    height: 'الطول',
    phase_01: 'الخطوة ٠١',
    phase_02: 'الخطوة ٠٢',
    phase_03: 'الخطوة ٠٣',
    phase_04: 'الخطوة ٠٤',
    select_your_plan: 'اختر خطتك',
    bespoke_selection: 'اختيارك',
    customize_your_menu: 'اختر المنيو الخاص بك',
    choose_collection_desc: 'اختر نوع الطعام الذي تفضله.',
    shipment_logistics: 'معلومات التوصيل',
    capture_location: 'تحديد موقعي',
    building: 'المبنى',
    street: 'الشارع',
    area_zone: 'المنطقة',
    blue_plate: 'اللوحة الزرقاء',
    doha_map: 'خريطة الدوحة',
    qatar_standard: 'معيار قطر',
    preferred_windows: 'أفضل وقت توصيل',
    checkout_auth: 'الدفع',
    secure_gateway_description: 'دفع آمن للبطاقات القطرية.',
    instant_settlement: 'دفع فوري',
    membership_protocol: 'خطة نشطة',
    legal_accept: 'أوافق على الشروط.',
    finalization: 'إنهاء',
    verify_order: 'تحقق من الطلب',
    final_audit: 'تدقيق نهائي قبل بدء وجباتك.',
    total_due: 'الإجمالي',
    activate_plan: 'بدء الوجبات',
    proceed: 'التالي',
    back: 'رجوع',
    month: 'شهر',

    // Booking Flow
    booking_package: 'خطة',
    booking_profile: 'معلوماتك',
    booking_date: 'الجدول',
    booking_details: 'ملفك الشخصي',
    booking_review: 'مراجعة',
    booking_title: 'خطة الاستشارة',
    booking_confirmed: 'تم التأكيد!',
    booking_success: 'ناجح!',
    subscription_success: 'تم الاشتراك!',
    subscription_activated_cod: 'الخطة نشطة. سنتواصل معك للدفع.',
    booking_locked: 'موعدك جاهز. تم إرسال التأكيد إلى:',
    return_home: 'العودة للرئيسية',
    select_collection: 'اختر نوع الطعام',
    biological_profile: 'معلوماتك الصحية',
    current_weight: 'الوزن الحالي',
    standing_height: 'الطول',
    target_ambition: 'هدفك',
    consultation_slot: 'وقت الدردشة',
    identity_verification: 'ملفك الشخصي',
    passport_id: 'البطاقة الشخصية / الجواز',
    email_address: 'البريد الإلكتروني',
    official: 'رسمي',
    mobile_number: 'رقم الجوال',
    whatsapp_linked: 'لديه واتساب',
    agree_terms: 'أوافق على الشروط.',
    summary_analysis: 'ملخص',
    target_launch: 'تاريخ البدء',
    account_holder: 'الاسم',
    register_consult: 'احجز الآن',
    Triangle: 'مثلث',
    triangle: 'مثلث',
    'Healthy Kitchen': 'المطبخ الصحي',
    undecided: 'غير متأكد',
    expert_recommendation: 'اختيار الخبراء',

    // Errors
    error_select_package: 'يرجى اختيار خطة.',
    error_metrics: 'يرجى إدخال الوزن والطول.',
    error_goal: 'يرجى اختيار الهدف.',
    error_slot: 'يرجى اختيار الوقت.',
    error_name: 'الاسم مطلوب.',
    error_email: 'البريد مطلوب.',
    error_phone: 'رقم الجوال مطلوب.',
    error_generic: 'خطأ. يرجى المحاولة ثانية.',
    legal_error: 'يرجى الموافقة للمتابعة.',

    // Goals & Levels
    'Weight Loss': 'فقدان الوزن',
    'Muscle Gain': 'بناء عضلات',
    'Maintain Weight': 'البقاء كما أنا',
    'Improve Energy': 'طاقة أكثر',
    'General Health': 'حياة صحية',
    'Athletic Performance': 'أداء رياضي',
    lose: 'فقدان وزن',
    maintain: 'محافظة',
    gain: 'بناء عضلات',
    sedentary: 'غير نشط',
    moderate: 'نشط',
    active: 'نشط جداً',

    // Payment
    card: 'بطاقة',
    applepay: 'Apple Pay',
    cod: 'الدفع عند الاستلام',

    // Dashboard
    member_dashboard: 'لوحة التحكم',
    shipment: 'توصيل',
    stats: 'إحصائيات',
    access_restricted: 'يرجى الانضمام',
    complete_consultation: 'يرجى اختيار خطة لرؤية لوحة التحكم.',
    return_to_site: 'رجوع',
    subscription_control: 'إدارة الخطة',
    pause_deliveries: 'إيقاف الوجبات',
    pause_desc: 'تحتاج استراحة؟ أوقف وجباتك مؤقتاً.',
    resume_now: 'استئناف الآن',
    pause_plan: 'إيقاف الخطة',
    safety_taste: 'الحساسية والمذاق',
    allergies_filter: 'حساسية',
    ingredient_dislikes: 'أطعمة لا أحبها',
    sign_out: 'خروج',
    this_week: 'هذا الأسبوع',
    next_week: 'الأسبوع القادم',
    weeks_ahead: 'أسابيع قادمة',
    starting: 'تبدأ في',
    my_rhythm: 'إيقاعي اليومي',
    your_week: 'أسبوعك',
    redeem: 'استبدال',
    chat: 'دردشة',
    nutrition_alignment: 'خطة الأكل',
    kcal_planned: 'سعرات',
    synced: 'محدث',
    confirmed: 'تم',
    heritage: 'محلي',
    allergen_alert: 'تنبيه حساسية',
    shipment_tracking: 'تتبع التوصيل',
    rider_on_route: 'السائق قادم',
    full_gps: 'تتبع مباشر',
    eta: 'الوقت المتبقي',
    minutes: 'دقائق',
    shipment_details: 'معلومات التوصيل',
    shipment_desc: 'تفاصيل التوصيل الخاصة بك.',
    building_number: 'المبنى',
    street_name: 'الشارع',
    zone_number: 'الزون',
    area_name: 'المنطقة',
    requirement: 'مطلوب',
    doha_district: 'منطقة الدوحة',
    shipment_instructions: 'ملاحظات التوصيل',
    optional: 'اختياري',
    cloud_synced: 'تم الحفظ',
    commit_data: 'حفظ',
    loyalty_assets: 'مكافآت',
    loyalty_units: 'نقاط',
    next_tier: 'المستوى القادم',
    expand_circle: 'دعوة أصدقاء',
    consistency: 'استمرارية',
    continuous_days: 'أيام متتالية',
    healthy_soul_trajectory: 'تقدم',
    your_progress: 'رحلتك',
    monitoring_bio: 'فحص صحتك.',
    waist: 'الخصر',
    hip: 'الحوض',
    syncing: 'جاري التحديث',
    confirm_entry: 'حفظ',
    awaiting_data: 'بانتظار المعلومات',

    // Onboarding
    define_identity: 'ملفك الشخصي.',
    male: 'ذكر',
    female: 'أنثى',
    bio_profile: 'معلومات صحية',
    continue: 'استمرار',

    // Menu
    menu_title: 'ماذا يوجد في المنيو',
    menu_subtitle: 'وجبات طازجة يحضرها الشيف أسبوعياً.',
    menu_search_placeholder: 'بحث عن طعام...',
    choices: 'خيارات',
    kcal: 'سعرة',
    calories: 'سعرات',
    qatari_heritage: 'خيار محلي',

    // Days
    Saturday: 'السبت',
    Sunday: 'الأحد',
    Monday: 'الاثنين',
    Tuesday: 'الثلاثاء',
    Wednesday: 'الأربعاء',
    Thursday: 'الخميس',
    Friday: 'الجمعة',

    // Meals
    breakfast: 'إفطار',
    lunch: 'غداء',
    dinner: 'عشاء',
    snacks: 'سناك',
    suhoor: 'سحور',
    iftar: 'إفطار',
    night_meal: 'وجبة ليلية',
    healthy_mind: 'عقل',
    healthy_body: 'جسد',
    healthy_soul: 'روح',
    pure_vitality: 'حيوية',

    // Footer
    footer_quick_links: 'روابط سريعة',
    footer_contact: 'اتصل بنا',
    footer_whatsapp: 'واتساب',
    footer_privacy: 'الخصوصية',
    footer_terms: 'الشروط',
    rider_access: 'دخول السائق',
    command_entry: 'دخول المطبخ',
    owner_chef: 'المالك',
    rider: 'سائق',
    sign_in: 'دخول',
    sign_up: 'ابدأ الخطة',
    email_identifier: 'البريد الإلكتروني',
    secure_passkey: 'كلمة السر',
    create_rider_account: 'تسجيل سائق',
    access_rider_portal: 'لوحة السائق',
    authorize_session: 'دخول',
    rider_flow: 'تطبيق السائق',
    ops_console: 'لوحة المطبخ',
    rider_onboarding_desc: 'يمكن للسائقين الدخول أو التسجيل هنا.',
    owner_login_desc: 'دخول المالك فقط.',
    unauthorized: 'لا يوجد وصول',
    provider_login: 'دخول المطبخ',
    triangle_healthy_kitchen: 'مطبخ المثلث الصحي',

    // Dashboard & Rhythm Keys
    keep_the_pace: 'واصل تقدمك الممتاز',
    weekly_streak: 'الاستمرارية الأسبوعية',
    next_milestone: 'المحطة القادمة',
    daily_activity: 'النشاط اليومي',
    your_dashboard: 'لوحة تحكمك',
    essential_plan_access: 'اشتراك الخطة الغذائية',
    progress: 'التقدم',
    access_label: 'الوصول',
    goal_label: 'الهدف',
    steps_label: 'الخطوات',
    days_label: 'أيام',
    balance_label: 'الرصيد',
    sync_now_btn: 'تحديث الآن',
    ops_command: 'عمليات المطبخ',
    live_feed: 'سجل النشاطات',
    inquiries: 'الحجوزات والاستفسارات',
    members: 'المشتركون',

    // Loading Screen
    securing_protocol: 'جاري البدء...',
    encrypting_session: 'فحص الملف',
    biometric_link: 'متصل',

    // Identity & Translation Sweep Keys
    'start your transformation': 'ابدأ رحلتك',
    'define your biology': 'أدخل معلوماتك الصحية',
    'editorial panel': 'لوحة المطبخ',
    'plans': 'الخطط',

    // Operational Center Keys
    'active subscribers': 'الأعضاء النشطون',
    'est. monthly revenue': 'الإيرادات الشهرية المتوقعة',
    'total inquiries': 'إجمالي الاستفسارات',
    'approved drivers': 'السائقون المعتمدون',
    'weekly order volume & revenue': 'حجم الطلبات والإيرادات الأسبوعية',
    'revenue trend based on active subscriber meal selections across doha': 'اتجاه الإيرادات بناءً على اختيارات الوجبات للأعضاء في الدوحة',
    'recent activity stream': 'نشاطات المطبخ الحديثة',
    'export kitchen csv': 'تصدير قائمة المطبخ CSV',
    'fleet drivers & approvals': 'سائقو التوصيل والموافقات',
    'approved driver': 'سائق معتمد',
    'pending approval': 'بانتظار الموافقة',
    'approve driver': 'اعتماد السائق',
    'revoke approval': 'إلغاء الاعتماد',
    'search bookings by name or email...': 'البحث عن الحجوزات بالاسم أو البريد...',
    'search subscribers by name, area, email...': 'البحث عن المشتركين بالاسم أو المنطقة...',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    try {
      if (!key || typeof key !== 'string') return '';
      const normalizedKey = key.trim().toLowerCase();

      const currentTranslations = translations[language] || translations['en'];

      const result = currentTranslations[normalizedKey] ||
                     currentTranslations[key] ||
                     translations['en'][normalizedKey] ||
                     translations['en'][key];

      return result !== undefined ? result : key;
    } catch (e) {
      return typeof key === 'string' ? key : '';
    }
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRtl, t }}>
      <div dir={isRtl ? 'rtl' : 'ltr'} className={isRtl ? 'font-sans' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
