import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRtl: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_packages: 'Plans',
    nav_menu: 'Menu',
    nav_how_it_works: 'How it works',
    nav_contact: 'Contact',
    nav_my_plan: 'My Plan',
    nav_book: 'Book Consultation',
    nav_dashboard: 'Dashboard',
    nav_join: 'Join',

    // Home Simplification
    what_is_triangle: 'What is Triangle?',
    what_get: 'What do I get?',
    what_get_desc: 'Fresh breakfast, lunch, and dinner. No cooking, no cleaning.',
    what_cost: 'How much does it cost?',
    starting_from: 'Healthy eating starting from QR 180/day.',
    how_start: 'How do I start?',
    step_1: 'Pick a Plan',
    step_2: 'Share Allergies',
    step_3: 'Get Food',
    excellent_experience: 'Excellent Experience',
    ready_to_eat_healthy: 'Ready to eat healthy?',

    // Auth & Profile
    login_title: 'Welcome Back',
    login_subtitle: 'Login to manage your plan',
    register_title: 'Start your Plan',
    register_subtitle: 'Create your account in seconds',
    login_button: 'Login',
    register_button: 'Get Started',
    forgot_password: 'Forgot password?',
    return_to_login: 'Back to login',
    identity_name: 'Name',
    operational_email: 'Email',
    security_key: 'Password',
    new_account: 'Need an account? Sign up',
    existing_account: 'Already have an account? Login',
    return_to_site: 'Return to Site',

    // Hero
    hero_title_1: 'Your Chef.',
    hero_title_2: 'Your Plan.',
    hero_title_3: 'Your Results.',
    hero_subtitle: 'Triangle Healthy Kitchen delivers healthy, chef-made meals to your door daily in Doha.',
    hero_cta_book: 'Start Plan',
    hero_cta_packages: 'View Plans',
    est_2017: 'Est. 2017',
    doha_excellence: 'Doha Excellence',
    doha_standard: 'Doha Standard',
    active_members: 'Active Members',
    collections: 'Collections',
    chef_support: 'Chef Support',
    transformation_title: 'Start your journey.',
    transformation_subtitle: 'Get your personal healthy meal plan today.',
    start_today: 'Start Today',
    view_menu: 'View Menu',
    all_rights_reserved: 'All Rights Reserved',
    Community: 'Community',
    Rewards: 'Rewards',
    Today: 'Today',
    Profile: 'Profile',
    healthy_mind_subtitle: 'CLARITY',
    healthy_body_subtitle: 'VITALITY',
    healthy_soul_subtitle: 'BALANCE',
    triangle_philosophy: 'Triangle Philosophy',
    one_triangle: 'One Triangle',
    three_pillars: 'Three Pillars',
    one_triangle_desc: 'One brand. Three pillars. A complete ecosystem for Doha.',
    mind_clarity_desc: 'Clear mind through healthy food.',
    body_vitality_desc: 'Feel better with whole foods.',
    soul_balance_desc: 'Balance in every dish.',
    visual_transparency_desc: 'Fresh ingredients. Excellent delivery.',
    chef_crafted_title: 'Chef Made',
    expert_quality_title: 'Best Quality',
    fresh_macro_meals: 'Fresh healthy meals prepared daily',
    simple_support: 'Support for your health and wellness',
    cleaner_path: 'A simple way to get results',
    identity_label: 'YOUR PROFILE',
    authenticating: 'CHECKING...',
    access_dashboard: 'OPEN DASHBOARD',
    secure_gateway: 'Secure Payment',
    fleet_online: 'Delivery Online',
    manual_assignment: 'Manual Assignment',
    active_revenue: 'Active Revenue',
    verified_units: 'Verified Units',
    active_ops: 'Active Ops',
    revenue_pulse: 'Revenue Pulse',
    refresh_signal: 'Refresh',
    find_identity: 'Find Profile...',
    assign_rider: 'Assign Driver',
    terminate_session: 'Logout',
    fully_booked: 'FULLY BOOKED',
    status_full: 'FULL',
    delivery_protocol: 'Delivery Plan',
    revenue: 'Revenue',
    awaiting_signal: 'Connecting...',
    realtime: 'LIVE',
    operational_intelligence: 'Kitchen Info',
    precision: 'Quality',
    online: 'Online',
    offline: 'Offline',
    approval_pending: 'Waiting for Approval',
    rider_verification_desc: 'Your account is being checked. Please wait.',
    assigned_stops: 'Assigned Deliveries',
    route_intelligence: 'Route Info',
    live_logistics: 'Live Delivery',
    gps_active: 'GPS Active',
    syncing_command: 'Connecting to Kitchen',
    todays_goal: 'Today\'s Goal',
    efficiency: 'Efficiency',
    stops: 'Deliveries',
    no_active_deliveries: 'No deliveries right now.',
    export_kitchen_prep: 'Export Kitchen Prep',
    prep_list_desc: 'Get the meal list for the Doha kitchen.',
    execute_bulk_assign: 'Assign All Drivers',
    bulk_assign_desc: 'Connect all members to drivers.',
    live_fleet_logistics: 'Live Delivery Map',
    total_label: 'Total',
    active_pulse: 'Live',
    muted_label: 'Muted',
    critical_intel: 'Health Info',
    dietary_restrictions: 'Allergies',
    exercise_routine: 'Exercise',
    health_notes: 'Health Notes',
    clinical_context: 'Healthy Context',
    duration_protocol: 'Plan Duration',
    days_count: 'Active Meal Days',
    duration_daily: 'Daily Trial',
    duration_weekly: 'Weekly Reset',
    duration_monthly: 'Monthly Plan',
    price_calculation: 'Simple Pricing',
    convenience_fee: 'Delivery Included',

    // Rhythm Calculator
    biological_audit: 'Health Assessment',
    discover_your_rhythm: 'Find your Calories',
    formulate_plan: 'Get Recommendation',
    weight: 'Weight',
    height: 'Height',
    energy_output: 'Activity Level',
    ambition: 'Goal',
    calculated_daily_target: 'Your Daily Goal',
    recommended_protocol: 'Recommended Plan',
    educational_estimate: 'This is an estimate. Professional advice is always best.',
    sedentary: 'Not Active',
    moderate: 'Active',
    active: 'Very Active',
    lose: 'Lose Weight',
    maintain: 'Maintain',
    gain: 'Build Muscle',
    'Rhythm.': 'Rhythm.',
    'rhythm.': 'Rhythm.',

    // Steps Synchronization
    YOUR_INFO: 'Your Info',
    PICK_PLAN: 'Pick Plan',
    DELIVERY_ADDRESS: 'Delivery Address',
    CREATE_ACCOUNT: 'Create Account',
    PAYMENT: 'Payment',
    REVIEW_START: 'Review & Start',
    your_info: 'Your Info',
    pick_plan: 'Pick Plan',
    delivery_address: 'Delivery Address',
    create_account: 'Create Account',
    payment: 'Payment',
    review_start: 'Review & Start',

    hiw_step1_title: 'Sign Up',
    hiw_step1_desc: 'Book your spot in 60 seconds.',
    hiw_step2_title: 'Your Health Info',
    hiw_step2_desc: 'Share your info for the perfect plan.',
    hiw_step4_title: 'Daily Meals',
    hiw_step4_desc: 'Fresh meals delivered daily to your door.',

    // About
    about_title: 'Healthy Meals, Delivered.',
    about_text_1: 'Since 2017, Triangle has been Doha\'s top choice for healthy meals.',
    about_text_2: 'We make fresh, tasty food to help you feel your best.',
    food_safety: 'Food Safety',
    food_safety_desc: 'Municipality Approved',
    bio_science: 'Healthy Science',
    bio_science_desc: 'Dietitian Led',
    artisanal: 'Chef Made',
    artisanal_desc: 'Fresh Every Day',
    logistics: 'Delivery',
    logistics_desc: 'GPS Tracked',
    years_of_excellence: 'Years in Doha',
    chef_crafted: 'Chef-Made',
    chef_crafted_desc: 'Fresh in our Doha kitchen',
    bio_aligned: 'Health-Matched',
    bio_aligned_desc: 'Made for your body',
    performance_focus: 'Feel Better',
    performance_focus_desc: 'Fuel for your mind and body',
    direct_service: 'Daily Delivery',
    direct_service_desc: 'To your door, 365 days',

    // Packages
    packages_title: 'Pick your Plan',
    packages_subtitle: 'Select the plan that fits your goals and energy.',
    '1100kcal': 'Essential Plan',
    '1400kcal': 'Daily Balance',
    '1500kcal': 'Performance Plan',
    signature_custom: 'Custom Plan',
    essential: 'Essential Plan',
    balance: 'Daily Balance',
    performance: 'Performance Plan',
    '1100kcal_desc': 'A simple, healthy plan to help you lose weight.',
    '1400kcal_desc': 'The perfect daily plan for balance and energy.',
    '1500kcal_desc': 'A personalized plan for active people.',
    signature_desc: 'Our best plan. Pick your own monthly menu.',
    daily_trial: '1 Day Pass',
    weekly_reset: '6 Day Pass',
    daily_trial_desc: '1 day of healthy meals. Great to try.',
    weekly_reset_desc: '6 days of healthy meals for your work week.',
    full_day_supply: 'Full Day of Meals',
    '6_day_supply': '6 Days of Meals',
    flexible_meals: 'Pick your meals',
    quick_access: 'Quick Access',
    short_term_focus: 'Short Term',
    best_for_weight_loss: 'Best for weight loss',
    for_active_lifestyles: 'For active people',
    bespoke_menu: 'Choose your menu',
    '4_weeks_flex': '4 Weeks (Full flexibility)',
    '2_meals_1_snack': '2 Meals + 1 Snack',
    '3_main_meals': '3 Main Meals',
    '3_meals_1_snack': '3 Meals + 1 Snack',
    '4_weeks_28_boxes': '4 Weeks (28 meals)',
    '4_weeks_28_boxes_pers': '4 Weeks (Personalized meals)',
    calories_per_day: 'Calories Per Day',
    balanced_nutrients: 'Balanced Nutrition',
    continuous_delivery: 'Daily Delivery',
    chef_tailored: 'Chef Made',
    based_on_metrics: 'Made for you',
    most_popular: 'Most Popular',
    premium: 'Healthy',
    qar: 'QAR',
    free_consultation: 'Free Chat',
    consultation: 'Chat',
    questions: 'Questions?',
    expert_recommendation: 'Expert Pick',

    // Mission
    mission_title: 'Our Mission',
    mission_intro: "We want to help you have a healthy mind, body, and soul",
    healthy_mind_title: "Healthy Mind",
    healthy_mind_desc: "We make meals that help you stay clear and happy.",
    healthy_body_title: "Healthy Body",
    healthy_body_desc: "Our meals give you energy and keep you healthy.",
    healthy_soul_title: "Healthy Soul",
    healthy_soul_desc: "We believe in good food and a good community.",
    mission_closing: "Healthy eating changes lives. We help you be your best.",

    // Dashboard
    member_dashboard: 'Your Dashboard',
    access: 'Access',
    shipment: 'Delivery',
    stats: 'Stats',
    access_restricted: 'Please Join',
    complete_consultation: 'Please pick a plan to see your dashboard.',
    subscription_control: 'Manage Plan',
    pause_deliveries: 'Pause Meals',
    pause_desc: 'Need a break? Pause your meals anytime.',
    resume_now: 'Resume Now',
    pause_plan: 'Pause Plan',
    safety_taste: 'Allergies & Taste',
    allergies_filter: 'Allergies',
    ingredient_dislikes: 'Foods I dislike',
    sign_out: 'Logout',
    this_week: 'This Week',
    next_week: 'Next Week',
    starting: 'Starts on',
    shipment_tracking: 'Shipment Tracking',
    rider_on_route: 'Driver is coming',
    full_gps: 'Live Tracking',
    shipment_details: 'Delivery Info',
    building: 'Building',
    street: 'Street',
    area_zone: 'Area',
    shipment_instructions: 'Delivery Notes',
    cloud_synced: 'Saved',

    // Booking Flow
    booking_package: 'Plan',
    booking_profile: 'Your Info',
    booking_date: 'Schedule',
    booking_details: 'Your Profile',
    booking_review: 'Review',
    booking_title: 'Consultation Plan',
    booking_confirmed: 'Confirmed!',
    booking_success: 'Successful!',
    subscription_success: 'Subscribed!',
    subscription_activated_cod: 'Plan Active. We will contact you for payment.',
    booking_locked: 'Your spot is ready. Confirmation sent to:',
    return_home: 'Go Home',
    select_collection: 'Pick Food Type',
    biological_profile: 'Your Health Info',
    current_weight: 'Current Weight',
    standing_height: 'Height',
    target_ambition: 'Your Goal',
    consultation_slot: 'Chat Time',
    identity_verification: 'Your Profile',
    passport_id: 'QID / Passport',
    email_address: 'Email',
    official: 'Official',
    mobile_number: 'Mobile',
    whatsapp_linked: 'Has WhatsApp',
    agree_terms: 'I agree to the terms.',
    summary_analysis: 'Summary',
    target_launch: 'Start Date',
    account_holder: 'Name',
    register_consult: 'Book Now',
    safety_desc_protocol: 'Allergy safety check. We filter your menu selections to avoid these items.',
    Triangle: 'Triangle',
    undecided: 'Not sure',

    // Errors
    error_select_package: 'Please pick a plan.',
    error_metrics: 'Please enter weight and height.',
    error_goal: 'Please pick a goal.',
    error_slot: 'Please pick a time.',
    error_name: 'Name is required.',
    error_email: 'Email is required.',
    error_phone: 'Phone is required.',
    error_generic: 'Error. Please try again.',
    legal_error: 'Please agree to proceed.',

    // Goals & Levels
    'Weight Loss': 'Lose Weight',
    'Muscle Gain': 'Build Muscle',
    'Maintain Weight': 'Stay the same',
    'Improve Energy': 'More Energy',
    'General Health': 'Healthy Living',
    'Athletic Performance': 'Performance',

    // Payment
    card: 'Card',
    applepay: 'Apple Pay',
    cod: 'Cash on Delivery',

    // Days
    Saturday: 'Saturday',
    Sunday: 'Sunday',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',

    // Meals
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snacks: 'Snacks',
    feed: 'Live Feed',
    bookings: 'Bookings',
    members: 'Members',
    rider_ops: 'Driver View',

    // Safety & Allergies
    safety_restrictions: 'Safety & Allergies',
    allergen_detected: 'NOT SAFE FOR YOU',
    safety_confirmed: 'SAFE FOR YOU',
    modify_restrictions: 'Update Allergies',
    fish: 'Fish',
    dairy: 'Dairy',
    eggs: 'Eggs',
    gluten: 'Gluten',
    seafood: 'Seafood',
    sesame: 'Sesame',
    nuts: 'Nuts',
    peanuts: 'Peanuts',
    soy: 'Soy',
    shellfish: 'Shellfish',
    mustard: 'Mustard',

    // Identity & Translation Sweep Keys
    'start your transformation': 'Start Today',
    'define your biology': 'Your Health Info',
    'editorial panel': 'Kitchen Panel',
    'plans': 'Plans',
    'menu': 'Menu',
    'suhoor': 'Suhoor',
    'iftar': 'Iftar',
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_about: 'حول',
    nav_packages: 'الخطط الغذائية',
    nav_menu: 'قائمة الطعام',
    nav_how_it_works: 'العملية',
    nav_contact: 'اتصال',
    nav_my_plan: 'خطتي',
    nav_book: 'حجز استشارة',
    nav_dashboard: 'لوحة التحكم',
    nav_join: 'انضم',

    // Home Simplification
    what_is_triangle: 'ما هو المثلث؟',
    what_get: 'ماذا أحصل؟',
    what_get_desc: 'إفطار وغداء وعشاء طازج. بدون طبخ أو تنظيف.',
    what_cost: 'ما هي التكلفة؟',
    starting_from: 'أكل صحي يبدأ من ١٨٠ ريال قطري يومياً.',
    how_start: 'كيف أبدأ؟',
    step_1: 'اختر خطة',
    step_2: 'أخبرنا بالحساسية',
    step_3: 'احصل على الطعام',
    excellent_experience: 'تجربة ممتازة',
    ready_to_eat_healthy: 'هل أنت مستعد للأكل الصحي؟',

    login_title: 'مرحباً بعودتك',
    login_subtitle: 'سجل الدخول لإدارة خطتك',
    register_title: 'ابدأ خطتك',
    register_subtitle: 'أنشئ حسابك في ثوانٍ',
    login_button: 'تسجيل الدخول',
    register_button: 'ابدأ الآن',
    forgot_password: 'نسيت كلمة السر؟',
    return_to_login: 'العودة لتسجيل الدخول',
    identity_name: 'الاسم الكامل',
    operational_email: 'البريد الإلكتروني',
    security_key: 'كلمة السر',
    new_account: 'جديد هنا؟ أنشئ حساباً',
    existing_account: 'لديك حساب بالفعل؟ سجل دخولك',
    return_to_site: 'الرجوع للموقع',

    hero_title_1: 'شيفك الخاص.',
    hero_title_2: 'خطتك الغذائية.',
    hero_title_3: 'نتائجك.',
    hero_subtitle: 'وجبات صحية من تحضير الشيف، تصلك يومياً لباب منزلك في الدوحة.',
    hero_cta_book: 'اشتراك',
    hero_cta_packages: 'عرض الخطط',
    est_2017: 'منذ ٢٠١٧',
    doha_excellence: 'تميز الدوحة',
    doha_standard: 'معيار الدوحة',
    active_members: 'أعضاء نشطون',
    collections: 'المجموعات',
    chef_support: 'دعم الشيف',
    transformation_title: 'ابدأ رحلة التغيير',
    transformation_subtitle: 'امنح نفسك خطة التغذية المخصصة اليوم.',
    start_today: 'ابدأ اليوم',
    view_menu: 'عرض قائمة الطعام',
    all_rights_reserved: 'جميع الحقوق محفوظة',

    // Safety & Allergies
    safety_restrictions: 'الأمان والقيود',
    allergen_detected: 'غير آمن لك',
    safety_confirmed: 'آمن لك',
    modify_restrictions: 'تحديث الحساسية',
    fish: 'سمك',
    dairy: 'ألبان',
    eggs: 'بيض',
    gluten: 'جلوتين',
    seafood: 'مأكولات بحرية',
    sesame: 'سمسم',
    nuts: 'مكسرات',
    peanuts: 'فول سوداني',
    soy: 'صويا',
    shellfish: 'قشريات',
    mustard: 'خردل',

    healthy_mind_subtitle: 'وضوح',
    healthy_body_subtitle: 'حيوية',
    healthy_soul_subtitle: 'توازن',
    triangle_philosophy: 'فلسفة المثلث',
    one_triangle: 'مثلث واحد',
    three_pillars: 'ثلاثة ركائز',
    one_triangle_desc: 'براند واحد. ثلاثة ركائز. نظام متكامل للدوحة.',
    mind_clarity_desc: 'عقل صافٍ من خلال أكل صحي.',
    body_vitality_desc: 'نشاط من خلال الأكل الطبيعي.',
    soul_balance_desc: 'توازن في كل طبق.',
    visual_transparency_desc: 'مكونات طازجة. توصيل ممتاز.',
    chef_crafted_title: 'من تحضير الشيف',
    portion_control_title: 'حصص مناسبة',
    expert_quality_title: 'أفضل جودة',
    fresh_macro_meals: 'وجبات صحية طازجة يومياً',
    simple_support: 'دعم لصحتك وعافيتك',
    cleaner_path: 'طريقة بسيطة لنتائج حقيقية',
    identity_label: 'الهوية',
    key_label: 'المفتاح',
    authenticating: 'جاري التحقق...',
    access_dashboard: 'لوحة التحكم',
    secure_gateway: 'دفع آمن',
    fleet_online: 'التوصيل متصل',
    manual_assignment: 'تعيين يدوي',
    active_revenue: 'الإيرادات',
    verified_units: 'الوحدات المعتمدة',
    active_ops: 'العمليات',
    revenue_pulse: 'نبض الإيرادات',
    refresh_signal: 'تحديث الإشارة',
    find_identity: 'البحث عن هوية...',
    assign_rider: 'تعيين سائق',
    terminate_session: 'خروج',
    fully_booked: 'مكتمل',
    status_full: 'مكتمل',
    delivery_protocol: 'خطة التوصيل',
    revenue: 'إيرادات',
    awaiting_signal: 'جاري الاتصال...',
    realtime: 'وقت حقيقي',
    operational_intelligence: 'ذكاء العمليات',
    precision: 'دقة',
    online: 'متصل',
    offline: 'غير متصل',
    approval_pending: 'الموافقة قيد الانتظار',
    rider_verification_desc: 'يتم فحص حسابك. يرجى الانتظار.',
    assigned_stops: 'التوقفات المحددة',
    route_intelligence: 'route_intelligence',
    live_logistics: 'لوجستيات مباشرة',
    gps_active: 'GPS نشط',
    syncing_command: 'مزامنة مع غرفة العمليات',
    todays_goal: 'هدف اليوم',
    efficiency: 'الكفاءة',
    stops: 'توقف',
    no_active_deliveries: 'لا يوجد توصيلات نشطة في قائمتك.',
    export_kitchen_prep: 'تصدير تحضير المطبخ',
    prep_list_desc: 'إنشاء ملف CSV لإنتاج ٢٤ ساعة لمرفق الدوحة.',
    execute_bulk_assign: 'تنفيذ التعيين الشامل',
    bulk_assign_desc: 'تحسين المسار وتعيين جميع الأعضاء النشطين للسائقين المعتمدين.',
    live_fleet_logistics: 'لوجستيات الأسطول المباشر',
    total_label: 'الإجمالي',
    active_pulse: 'نبض نشط',
    muted_label: 'صامت',
    critical_intel: 'معلومات هامة',
    dietary_restrictions: 'القيود الغذائية',
    exercise_routine: 'روتين التمرين',
    health_notes: 'ملاحظات صحية',
    clinical_context: 'سياق صحي',
    duration_protocol: 'مدة الاشتراك',
    days_count: 'أيام التوصيل النشطة',
    duration_daily: 'تجربة يومية',
    duration_weekly: 'إعادة ضبط أسبوعية',
    duration_monthly: 'خطة شهرية',
    price_calculation: 'تسعير موحد',
    convenience_fee: 'شامل رسوم اللوجستيات',
    hiw_step1_title: 'أخبرنا بنمط حياتك.',
    hiw_step1_desc: 'حدد معاييرك الصحية للتغذية من خلال التقييم الخاص بنا.',
    hiw_step2_title: 'نحن نصيغ الخطة.',
    hiw_step2_desc: 'يقوم الطهاة وأخصائيو التغذية لدينا بهندسة قائمة طعام تتماشى مع حالتك القصوى.',
    hiw_step4_title: 'افتح الباب.',
    hiw_step4_desc: 'إمداد طازج يصل إلى باب منزلك كل صباح في جميع أنحاء الدوحة.',
    food_safety: 'سلامة الغذاء',
    food_safety_desc: 'معتمد من بلدية الدوحة',
    bio_science: 'العلوم الحيوية',
    bio_science_desc: 'بإشراف أخصائي تغذية إكلينيكي',
    artisanal: 'حرفي',
    artisanal_desc: 'طازج ومعد من قبل الشيف يومياً',
    logistics: 'لوجستيات',
    logistics_desc: 'تتبع مباشر للأسطول عبر GPS',

    // Rhythm Calculator
    biological_audit: 'التقييم الصحي',
    discover_your_rhythm: 'احسب سعراتك الحرارية',
    formulate_plan: 'احصل على التوصية',
    weight: 'الوزن',
    height: 'الطول',
    energy_output: 'مستوى النشاط',
    ambition: 'الهدف',
    calculated_daily_target: 'هدفك اليومي',
    recommended_protocol: 'الخطة الموصى بها',
    educational_estimate: 'هذا مجرد تقدير. النصيحة المهنية هي الأفضل دائماً.',
    sedentary: 'غير نشط',
    moderate: 'نشط',
    active: 'نشط جداً',
    lose: 'فقدان وزن',
    maintain: 'محافظة',
    gain: 'بناء عضلات',
    'Rhythm.': 'إيقاعك.',
    'rhythm.': 'إيقاعك.',

    // Steps Synchronization
    your_info: 'معلوماتك',
    pick_plan: 'اختر خطة',
    delivery_address: 'عنوان التوصيل',
    create_account: 'إنشاء حساب',
    payment: 'الدفع',
    review_start: 'المراجعة والبدء',

    about_title: 'تغذية مخصصة، تصلك أينما كنت.',
    about_text_1: 'منذ عام ٢٠١٧، كان المثلث هو المعيار في الدوحة للتغذية عالية الأداء والتميز في الطهي.',
    about_text_2: 'نحن ندمج نكهات التراث التقليدي مع العلوم الحيوية الحديثة لتغذية أسلوب حياة مجتمعنا.',
    years_of_excellence: 'سنوات من التميز في الدوحة',
    chef_crafted: 'معد من قبل الشيف',
    chef_crafted_desc: 'صنع يدوياً طازجاً في مطبخنا بالدوحة',
    bio_aligned: 'توافق صحي',
    bio_aligned_desc: 'محسوب وفقاً لمقاييسك الدقيقة',
    performance_focus: 'تركيز الأداء',
    performance_focus_desc: 'تغذية الحالات الذهنية والبدنية القصوى',
    direct_service: 'خدمة مباشرة',
    direct_service_desc: 'توصيل لباب المنزل، ٣٦٥ يوماً',

    packages_title: 'تغذية منسقة',
    packages_subtitle: 'اختر مستوى الوقود المستهدف لقاعدتك الصحية وإنتاج الطاقة اليومي.',
    '1100kcal': 'خطة أساسية',
    '1400kcal': 'توازن يومي',
    '1500kcal': 'خطة الأداء',
    signature_custom: 'مخصص للتميز',
    essential: 'خطة أساسية',
    balance: 'توازن يومي',
    performance: 'الأداء',
    '1100kcal_desc': 'خطة مركزة ومتحكم في سعراتها الحرارية مصممة لفقدان الوزن الصحي والمستقر.',
    '1400kcal_desc': 'خطة الوجبات اليومية المثالية لتغذية متوازنة وطاقة مستدامة.',
    '1500kcal_desc': 'خطة مخصصة بالكامل لأنماط الحياة النشطة وأهداف الأداء.',
    signature_desc: 'قمة تناول الطعام في المثلث. اختر منيو شهرك بالكامل يدوياً من مجموعاتنا المميزة.',
    daily_trial: 'تصريح يومي',
    weekly_reset: 'تصريح أسبوعي',
    daily_trial_desc: 'إمداد يومي دقيق. مثالي للمسافرين أو للتجربة قصيرة المدى.',
    weekly_reset_desc: 'ستة أيام من الإمداد. ركز على أهدافك خلال أسبوع العمل.',
    full_day_supply: 'إمداد يوم كامل',
    '6_day_supply': 'إمداد ٦ أيام',
    flexible_meals: 'اختيارات مرنة',
    quick_access: 'وصول سريع',
    short_term_focus: 'تركيز قصير المدى',
    best_for_weight_loss: 'الأفضل لفقدان الوزن',
    for_active_lifestyles: 'لأنماط الحياة النشطة',
    bespoke_menu: 'منيو مخصص بالكامل',
    '4_weeks_flex': '٤ أسابيع (مرونة غير محدودة)',
    '2_meals_1_snack': 'وجبتين + سناك واحد',
    '3_main_meals': '٣ وجبات رئيسية',
    '3_meals_1_snack': '٣ وجبات + سناك واحد',
    '4_weeks_28_boxes': '٤ أسابيع (٢٨ صندوقاً)',
    '4_weeks_28_boxes_pers': '٤ أسابيع (٢٨ صندوقاً مخصصاً)',
    calories_per_day: 'سعرة حرارية في اليوم',
    balanced_nutrients: 'عناصر غذائية متوازنة',
    continuous_delivery: 'توصيل مستمر',
    chef_tailored: 'مفصل من قبل الشيف',
    based_on_metrics: 'بناءً على مقاييسك',
    most_popular: 'الأكثر شعبية',
    premium: 'مميز',
    qar: 'ريال قطري',
    free_consultation: 'استشارة مجانية',
    consultation: 'استشارة',
    questions: 'أسئلة؟',
    expert_recommendation: 'توصية الخبراء',

    mission_title: 'مهمتنا',
    mission_intro: "مهمتنا في مطبخ المثلث الصحي هي إلهام الأفراد لخلق عقل وجسد وروح صحية",
    healthy_mind_title: "عقل سليم",
    healthy_mind_desc: "نحن نركز على توفير الوجبات التي تعزز الوضوح العقلي والرفاهية العاطفية، حيث أن تناول الأطعمة المغذية يمكن أن يعزز الحالة المزاجية ويقلل من التوتر.",
    healthy_body_title: "جسم سليم",
    healthy_body_desc: "تم تصميم وجباتنا لتغذية الجسم، وتوفير العناصر الغذائية الأساسية التي تدعم الصحة البدنية وتزيد من مستويات الطاقة.",
    healthy_soul_title: "روح سليمة",
    healthy_soul_desc: "نؤمن أيضاً بأهمية التواصل مع الذات والآخرين، وتعزيز الشعور بالمجتمع واليقظة الذهنية من خلال طعامنا.",
    mission_closing: "نحن نؤمن بأن الأكل الصحي يحفز النمو ويغير الحياة، ويمكّن الجميع من الازدهار في جميع جوانب الحياة، مما يجعلهم أفضل نسخة من أنفسهم.",

    member_dashboard: 'لوحة التحكم',
    access: 'دخول',
    shipment: 'توصيل',
    stats: 'إحصائيات',
    access_restricted: 'الوصول مقيد',
    complete_consultation: 'يرجى اختيار خطة لرؤية لوحة التحكم.',
    subscription_control: 'إدارة الخطة',
    pause_deliveries: 'إيقاف الوجبات',
    pause_desc: 'تحتاج استراحة؟ أوقف وجباتك مؤقتاً.',
    resume_now: 'استئناف الآن',
    pause_plan: 'إيقاف الخطة',
    safety_taste: 'الحساسية والمذاق',
    allergies_filter: 'حساسية',
    ingredient_dislikes: 'أطعمة لا أحبها',
    sign_out: 'خروج',
    this_week: 'هذا الأسبوع',
    next_week: 'الأسبوع القادم',
    starting: 'تبدأ في',
    shipment_tracking: 'تتبع التوصيل',
    rider_on_route: 'السائق قادم',
    full_gps: 'تتبع مباشر',
    shipment_details: 'تفاصيل التوصيل',
    building: 'المبنى',
    street: 'الشارع',
    area_zone: 'المنطقة',
    shipment_instructions: 'ملاحظات التوصيل',
    cloud_synced: 'تم الحفظ',

    booking_package: 'المجموعة',
    booking_profile: 'الملف الصحي',
    booking_date: 'الجدول',
    booking_details: 'حسابك الشخصي',
    booking_review: 'التدقيق',
    booking_title: 'حجز',
    booking_confirmed: 'تم تأكيد الحجز',
    booking_success: 'تم الحجز بنجاح',
    booking_locked: 'تم تأمين موعدك. تم إرسال التأكيد إلى:',
    return_home: 'العودة للرئيسية',
    select_collection: 'اختر نوع الطعام',
    biological_profile: 'الملف الصحي',
    current_weight: 'الوزن الحالي',
    standing_height: 'الطول',
    target_ambition: 'هدفك',
    consultation_slot: 'موعد الاستشارة',
    identity_verification: 'التحقق من الحساب',
    passport_id: 'البطاقة الشخصية / الجواز',
    email_address: 'البريد الإلكتروني',
    official: 'رسمي',
    mobile_number: 'رقم الجوال',
    whatsapp_linked: 'لديه واتساب',
    agree_terms: 'أوافق على الشروط.',
    summary_analysis: 'ملخص التحليل',
    target_launch: 'موعد البدء',
    account_holder: 'صاحب الحساب',
    register_consult: 'احجز الآن',
    safety_desc_protocol: 'فحص الحساسية. نقوم بتصفية خيارات المنيو لتجنب هذه العناصر.',
    Triangle: 'Triangle',
    undecided: 'غير متأكد',

    error_select_package: 'يرجى اختيار مجموعة للمتابعة.',
    error_metrics: 'يرجى إدخال الوزن والطول.',
    error_goal: 'يرجى اختيار الهدف.',
    error_slot: 'يرجى اختيار الوقت.',
    error_name: 'الاسم مطلوب.',
    error_email: 'البريد مطلوب.',
    error_phone: 'رقم الجوال مطلوب.',
    error_generic: 'خطأ. يرجى المحاولة ثانية.',
    legal_error: 'يرجى المواقة للمتابعة.',

    'Weight Loss': 'فقدان الوزن',
    'Muscle Gain': 'بناء عضلات',
    'Maintain Weight': 'الحفاظ على الوزن',

    Saturday: 'السبت',
    Sunday: 'الأحد',
    Monday: 'الاثنين',
    Tuesday: 'الثلاثاء',
    Wednesday: 'الأربعاء',
    Thursday: 'الخميس',
    Friday: 'الجمعة',

    breakfast: 'إفطار',
    lunch: 'غداء',
    dinner: 'عشاء',
    snacks: 'سناك',
    feed: 'البث المباشر',
    bookings: 'الحجوزات',
    members: 'الأعضاء',
    rider_ops: 'عرض السائق',

    Today: 'اليوم',
    Community: 'المجتمع',
    Rewards: 'المكافآت',
    Profile: 'الحساب',
    HOME: 'الرئيسية',
    securing_protocol: 'جاري البدء...',
    encrypting_session: 'فحص الملف',
    biometric_link: 'متصل',

    // Identity & Translation Sweep Keys
    'start your transformation': 'ابدأ رحلتك',
    'define your biology': 'أدخل معلوماتك الصحية',
    'editorial panel': 'لوحة المطبخ',
    'plans': 'الخطط',
    'menu': 'المنيو',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    try {
      if (!key || typeof key !== 'string') return '';
      const normalizedKey = key.trim().toLowerCase();

      const currentTranslations = translations[language] || translations['en'];

      const result = currentTranslations[normalizedKey] ||
                     currentTranslations[key] ||
                     translations['en'][normalizedKey] ||
                     translations['en'][key];

      return result !== undefined ? result : key;
    } catch (e) {
      return typeof key === 'string' ? key : '';
    }
  };

  const isRtl = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRtl, t }}>
      <div dir={isRtl ? 'rtl' : 'ltr'} className={isRtl ? 'font-sans' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
